/**
 * 3gpp-5glan-pp
 * API for 5G LAN Parameter Provision. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * 5GLanParametersProvisionPatch.h
 *
 *
 */

#ifndef 5GLanParametersProvisionPatch_H_
#define 5GLanParametersProvisionPatch_H_

#include "5GLanParametersPatch.h"
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class 5GLanParametersProvisionPatch {
 public:
  5GLanParametersProvisionPatch();
  virtual ~5GLanParametersProvisionPatch() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream & msg) const;

  bool operator==(const 5GLanParametersProvisionPatch & rhs) const;
  bool operator!=(const 5GLanParametersProvisionPatch & rhs) const;

  /////////////////////////////////////////////
  /// 5GLanParametersProvisionPatch members

  /// <summary>
  ///
  /// </summary>
  5GLanParametersPatch getR5gLanParamsPatch() const;
  void setR5gLanParamsPatch(5GLanParametersPatch const& value);
  bool r5gLanParamsPatchIsSet() const;
  void unsetr_5gLanParamsPatch();

  friend void to_json(
      nlohmann::json & j, const 5GLanParametersProvisionPatch & o);
  friend void from_json(
      const nlohmann::json& j, 5GLanParametersProvisionPatch & o);

 protected:
  5GLanParametersPatch m_r_5gLanParamsPatch;
  bool m_r_5gLanParamsPatchIsSet;

  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream & msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* 5GLanParametersProvisionPatch_H_ */
