/**
 * 3gpp-5glan-pp
 * API for 5G LAN Parameter Provision. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "5GLanParametersProvisionPatch.h"
#include "Helpers.h"

#include <sstream>

namespace oai::nef::model {

5GLanParametersProvisionPatch ::5GLanParametersProvisionPatch() {
  m_r_5gLanParamsPatchIsSet = false;
}

void 5GLanParametersProvisionPatch ::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool 5GLanParametersProvisionPatch ::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool 5GLanParametersProvisionPatch ::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "5GLanParametersProvisionPatch" : pathPrefix;

  return success;
}

bool 5GLanParametersProvisionPatch ::operator==(
    const 5GLanParametersProvisionPatch & rhs) const {
  return

      ((!r5gLanParamsPatchIsSet() && !rhs.r5gLanParamsPatchIsSet()) ||
       (r5gLanParamsPatchIsSet() && rhs.r5gLanParamsPatchIsSet() &&
        getR5gLanParamsPatch() == rhs.getR5gLanParamsPatch()))

          ;
}

bool 5GLanParametersProvisionPatch ::operator!=(
    const 5GLanParametersProvisionPatch & rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const 5GLanParametersProvisionPatch & o) {
  j = nlohmann::json();
  if (o.r5gLanParamsPatchIsSet())
    j["5gLanParamsPatch"] = o.m_r_5gLanParamsPatch;
}

void from_json(const nlohmann::json& j, 5GLanParametersProvisionPatch & o) {
  if (j.find("5gLanParamsPatch") != j.end()) {
    j.at("5gLanParamsPatch").get_to(o.m_r_5gLanParamsPatch);
    o.m_r_5gLanParamsPatchIsSet = true;
  }
}

5GLanParametersPatch 5GLanParametersProvisionPatch ::getR5gLanParamsPatch()
    const {
  return m_r_5gLanParamsPatch;
}
void 5GLanParametersProvisionPatch ::setR5gLanParamsPatch(
    5GLanParametersPatch const& value) {
  m_r_5gLanParamsPatch      = value;
  m_r_5gLanParamsPatchIsSet = true;
}
bool 5GLanParametersProvisionPatch ::r5gLanParamsPatchIsSet() const {
  return m_r_5gLanParamsPatchIsSet;
}
void 5GLanParametersProvisionPatch ::unsetr_5gLanParamsPatch() {
  m_r_5gLanParamsPatchIsSet = false;
}

}  // namespace oai::nef::model
