/**
 * 3gpp-5glan-pp
 * API for 5G LAN Parameter Provision. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * 5GLanParametersProvision.h
 *
 *
 */

#ifndef 5GLanParametersProvision_H_
#define 5GLanParametersProvision_H_

#include <string>
#include "5GLanParameters.h"
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class 5GLanParametersProvision {
 public:
  5GLanParametersProvision();
  virtual ~5GLanParametersProvision() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream & msg) const;

  bool operator==(const 5GLanParametersProvision & rhs) const;
  bool operator!=(const 5GLanParametersProvision & rhs) const;

  /////////////////////////////////////////////
  /// 5GLanParametersProvision members

  /// <summary>
  /// string formatted according to IETF RFC 3986 identifying a referenced
  /// resource.
  /// </summary>
  std::string getSelf() const;
  void setSelf(std::string const& value);
  bool selfIsSet() const;
  void unsetSelf();
  /// <summary>
  ///
  /// </summary>
  5GLanParameters getR5gLanParams() const;
  void setR5gLanParams(5GLanParameters const& value);
  /// <summary>
  ///
  /// </summary>
  std::string getSuppFeat() const;
  void setSuppFeat(std::string const& value);

  friend void to_json(nlohmann::json & j, const 5GLanParametersProvision & o);
  friend void from_json(const nlohmann::json& j, 5GLanParametersProvision & o);

 protected:
  std::string m_Self;
  bool m_SelfIsSet;
  5GLanParameters m_r_5gLanParams;

  std::string m_SuppFeat;

  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream & msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* 5GLanParametersProvision_H_ */
