/**
 * 3gpp-5glan-pp
 * API for 5G LAN Parameter Provision. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * 5GLanParametersPatch.h
 *
 *
 */

#ifndef 5GLanParametersPatch_H_
#define 5GLanParametersPatch_H_

#include <string>
#include "AppDescriptorRm.h"
#include <map>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class 5GLanParametersPatch {
 public:
  5GLanParametersPatch();
  virtual ~5GLanParametersPatch() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream & msg) const;

  bool operator==(const 5GLanParametersPatch & rhs) const;
  bool operator!=(const 5GLanParametersPatch & rhs) const;

  /////////////////////////////////////////////
  /// 5GLanParametersPatch members

  /// <summary>
  ///
  /// </summary>
  std::map<std::string, std::string> getGpsis() const;
  void setGpsis(std::map<std::string, std::string> const& value);
  bool gpsisIsSet() const;
  void unsetGpsis();
  /// <summary>
  ///
  /// </summary>
  std::map<std::string, AppDescriptorRm> getAppDesps() const;
  void setAppDesps(std::map<std::string, AppDescriptorRm> const& value);
  bool appDespsIsSet() const;
  void unsetAppDesps();

  friend void to_json(nlohmann::json & j, const 5GLanParametersPatch & o);
  friend void from_json(const nlohmann::json& j, 5GLanParametersPatch & o);

 protected:
  std::map<std::string, std::string> m_Gpsis;
  bool m_GpsisIsSet;
  std::map<std::string, AppDescriptorRm> m_AppDesps;
  bool m_AppDespsIsSet;

  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream & msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* 5GLanParametersPatch_H_ */
