/**
 * 3gpp-5glan-pp
 * API for 5G LAN Parameter Provision. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "AaaUsage.h"
#include "Helpers.h"

#include <sstream>

namespace oai::nef::model {

AaaUsage::AaaUsage() {}

void AaaUsage::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool AaaUsage::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool AaaUsage::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "AaaUsage" : pathPrefix;

  return success;
}

bool AaaUsage::operator==(const AaaUsage& rhs) const {
  return

      ;
}

bool AaaUsage::operator!=(const AaaUsage& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const AaaUsage& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, AaaUsage& o) {}

}  // namespace oai::nef::model
