/**
 * 3gpp-5glan-pp
 * API for 5G LAN Parameter Provision. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AaaUsage.h
 *
 * Possible values are   - AUTH: secondary authentication/authorization needed
 * from DN-AAA server   - IP_ALLOC: UE IP address allocation needed from DN-AAA
 * server
 */

#ifndef AaaUsage_H_
#define AaaUsage_H_

#include "AaaUsage_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
/// Possible values are   - AUTH: secondary authentication/authorization needed
/// from DN-AAA server   - IP_ALLOC: UE IP address allocation needed from DN-AAA
/// server
/// </summary>
class AaaUsage {
 public:
  AaaUsage();
  virtual ~AaaUsage() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const AaaUsage& rhs) const;
  bool operator!=(const AaaUsage& rhs) const;

  /////////////////////////////////////////////
  /// AaaUsage members

  friend void to_json(nlohmann::json& j, const AaaUsage& o);
  friend void from_json(const nlohmann::json& j, AaaUsage& o);

 protected:
  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* AaaUsage_H_ */
