/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "Accuracy.h"
#include "Helpers.h"

#include <sstream>

namespace oai::nef::model {

Accuracy::Accuracy() {}

void Accuracy::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool Accuracy::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool Accuracy::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "Accuracy" : pathPrefix;

  return success;
}

bool Accuracy::operator==(const Accuracy& rhs) const {
  return

      ;
}

bool Accuracy::operator!=(const Accuracy& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Accuracy& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, Accuracy& o) {}

}  // namespace oai::nef::model
