/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Accuracy.h
 *
 * Possible values are - LOW: Low accuracy. - HIGH: High accuracy.
 */

#ifndef Accuracy_H_
#define Accuracy_H_

#include "Accuracy_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
/// Possible values are - LOW: Low accuracy. - HIGH: High accuracy.
/// </summary>
class Accuracy {
 public:
  Accuracy();
  virtual ~Accuracy() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const Accuracy& rhs) const;
  bool operator!=(const Accuracy& rhs) const;

  /////////////////////////////////////////////
  /// Accuracy members

  friend void to_json(nlohmann::json& j, const Accuracy& o);
  friend void from_json(const nlohmann::json& j, Accuracy& o);

 protected:
  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* Accuracy_H_ */
