/**
 * 3gpp-traffic-influence
 * API for AF traffic influence © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * AfResultInfo.h
 *
 *
 */

#ifndef AfResultInfo_H_
#define AfResultInfo_H_

#include "AfResultStatus.h"
#include "RouteToLocation.h"
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class AfResultInfo {
 public:
  AfResultInfo();
  virtual ~AfResultInfo() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const AfResultInfo& rhs) const;
  bool operator!=(const AfResultInfo& rhs) const;

  /////////////////////////////////////////////
  /// AfResultInfo members

  /// <summary>
  ///
  /// </summary>
  AfResultStatus getAfStatus() const;
  void setAfStatus(AfResultStatus const& value);
  /// <summary>
  ///
  /// </summary>
  RouteToLocation getTrafficRoute() const;
  void setTrafficRoute(RouteToLocation const& value);
  bool trafficRouteIsSet() const;
  void unsetTrafficRoute();

  friend void to_json(nlohmann::json& j, const AfResultInfo& o);
  friend void from_json(const nlohmann::json& j, AfResultInfo& o);

 protected:
  AfResultStatus m_AfStatus;

  RouteToLocation m_TrafficRoute;
  bool m_TrafficRouteIsSet;

  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* AfResultInfo_H_ */
