/**
 * Nnef_EventExposure
 * NEF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "ExceptionId.h"
#include "Helpers.h"

#include <sstream>

namespace oai::nef::model {

ExceptionId::ExceptionId() {}

void ExceptionId::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool ExceptionId::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool ExceptionId::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "ExceptionId" : pathPrefix;

  return success;
}

bool ExceptionId::operator==(const ExceptionId& rhs) const {
  return true

      ;
}

bool ExceptionId::operator!=(const ExceptionId& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const ExceptionId& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, ExceptionId& o) {}

}  // namespace oai::nef::model
