/**
 * Nnef_EventExposure
 * NEF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "FlowDirection.h"
#include "Helpers.h"

#include <sstream>

namespace oai::nef::model {

FlowDirection::FlowDirection() {}

void FlowDirection::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool FlowDirection::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool FlowDirection::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "FlowDirection" : pathPrefix;

  return success;
}

bool FlowDirection::operator==(const FlowDirection& rhs) const {
  return true

      ;
}

bool FlowDirection::operator!=(const FlowDirection& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const FlowDirection& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, FlowDirection& o) {}

}  // namespace oai::nef::model
