/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * GeographicArea.h
 *
 *
 */

#ifndef GeographicArea_H_
#define GeographicArea_H_

#include "PointUncertaintyCircle.h"
#include "Point.h"
#include "PointUncertaintyEllipse.h"
#include "GeographicalCoordinates.h"
#include "PointAltitude.h"
#include "UncertaintyEllipse.h"
#include "EllipsoidArc.h"
#include "PointAltitudeUncertainty.h"
#include "Polygon.h"
#include <vector>
#include "SupportedGADShapes.h"
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class GeographicArea {
 public:
  GeographicArea();
  virtual ~GeographicArea() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const GeographicArea& rhs) const;
  bool operator!=(const GeographicArea& rhs) const;

  /////////////////////////////////////////////
  /// GeographicArea members

  /// <summary>
  ///
  /// </summary>
  SupportedGADShapes getShape() const;
  void setShape(SupportedGADShapes const& value);
  /// <summary>
  ///
  /// </summary>
  GeographicalCoordinates getPoint() const;
  void setPoint(GeographicalCoordinates const& value);
  /// <summary>
  ///
  /// </summary>
  float getUncertainty() const;
  void setUncertainty(float const value);
  /// <summary>
  ///
  /// </summary>
  UncertaintyEllipse getUncertaintyEllipse() const;
  void setUncertaintyEllipse(UncertaintyEllipse const& value);
  /// <summary>
  ///
  /// </summary>
  int32_t getConfidence() const;
  void setConfidence(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  std::vector<GeographicalCoordinates> getPointList() const;
  void setPointList(std::vector<GeographicalCoordinates> const& value);
  /// <summary>
  ///
  /// </summary>
  double getAltitude() const;
  void setAltitude(double const value);
  /// <summary>
  ///
  /// </summary>
  float getUncertaintyAltitude() const;
  void setUncertaintyAltitude(float const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getInnerRadius() const;
  void setInnerRadius(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  float getUncertaintyRadius() const;
  void setUncertaintyRadius(float const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getOffsetAngle() const;
  void setOffsetAngle(int32_t const value);
  /// <summary>
  ///
  /// </summary>
  int32_t getIncludedAngle() const;
  void setIncludedAngle(int32_t const value);

  friend void to_json(nlohmann::json& j, const GeographicArea& o);
  friend void from_json(const nlohmann::json& j, GeographicArea& o);

 protected:
  SupportedGADShapes m_Shape;

  GeographicalCoordinates m_Point;

  float m_Uncertainty;

  UncertaintyEllipse m_UncertaintyEllipse;

  int32_t m_Confidence;

  std::vector<GeographicalCoordinates> m_PointList;

  double m_Altitude;

  float m_UncertaintyAltitude;

  int32_t m_InnerRadius;

  float m_UncertaintyRadius;

  int32_t m_OffsetAngle;

  int32_t m_IncludedAngle;

  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* GeographicArea_H_ */
