/**
 * 3gpp-iptvconfiguration
 * API for IPTV configuration. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * IptvConfigDataPatch.h
 *
 *
 */

#ifndef IptvConfigDataPatch_H_
#define IptvConfigDataPatch_H_

#include "MulticastAccessControl.h"
#include <map>
#include <vector>
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class IptvConfigDataPatch {
 public:
  IptvConfigDataPatch();
  virtual ~IptvConfigDataPatch() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const IptvConfigDataPatch& rhs) const;
  bool operator!=(const IptvConfigDataPatch& rhs) const;

  /////////////////////////////////////////////
  /// IptvConfigDataPatch members

  /// <summary>
  ///
  /// </summary>
  std::map<std::string, MulticastAccessControl> getMultiAccCtrls() const;
  void setMultiAccCtrls(
      std::map<std::string, MulticastAccessControl> const& value);
  bool multiAccCtrlsIsSet() const;
  void unsetMultiAccCtrls();

  friend void to_json(nlohmann::json& j, const IptvConfigDataPatch& o);
  friend void from_json(const nlohmann::json& j, IptvConfigDataPatch& o);

 protected:
  std::map<std::string, MulticastAccessControl> m_MultiAccCtrls;
  bool m_MultiAccCtrlsIsSet;

  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* IptvConfigDataPatch_H_ */
