/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * LcsQosClass.h
 *
 *
 */

#ifndef LcsQosClass_H_
#define LcsQosClass_H_

#include "LcsQosClass_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class LcsQosClass {
 public:
  LcsQosClass();
  virtual ~LcsQosClass() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const LcsQosClass& rhs) const;
  bool operator!=(const LcsQosClass& rhs) const;

  /////////////////////////////////////////////
  /// LcsQosClass members

  friend void to_json(nlohmann::json& j, const LcsQosClass& o);
  friend void from_json(const nlohmann::json& j, LcsQosClass& o);

 protected:
  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* LcsQosClass_H_ */
