/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "LdrType.h"
#include "Helpers.h"

#include <sstream>

namespace oai::nef::model {

LdrType::LdrType() {}

void LdrType::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool LdrType::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool LdrType::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success                  = true;
  const std::string _pathPrefix = pathPrefix.empty() ? "LdrType" : pathPrefix;

  return success;
}

bool LdrType::operator==(const LdrType& rhs) const {
  return

      ;
}

bool LdrType::operator!=(const LdrType& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const LdrType& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, LdrType& o) {}

}  // namespace oai::nef::model
