/**
 * 3gpp-5glan-pp
 * API for 5G LAN Parameter Provision. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PduSessionType.h"
#include "Helpers.h"

#include <sstream>

namespace oai::nef::model {

PduSessionType::PduSessionType() {}

void PduSessionType::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool PduSessionType::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool PduSessionType::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "PduSessionType" : pathPrefix;

  return success;
}

bool PduSessionType::operator==(const PduSessionType& rhs) const {
  return

      ;
}

bool PduSessionType::operator!=(const PduSessionType& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PduSessionType& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, PduSessionType& o) {}

}  // namespace oai::nef::model
