/**
 * 3gpp-5glan-pp
 * API for 5G LAN Parameter Provision. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * PduSessionType.h
 *
 *
 */

#ifndef PduSessionType_H_
#define PduSessionType_H_

#include "PduSessionType_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class PduSessionType {
 public:
  PduSessionType();
  virtual ~PduSessionType() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const PduSessionType& rhs) const;
  bool operator!=(const PduSessionType& rhs) const;

  /////////////////////////////////////////////
  /// PduSessionType members

  friend void to_json(nlohmann::json& j, const PduSessionType& o);
  friend void from_json(const nlohmann::json& j, PduSessionType& o);

 protected:
  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* PduSessionType_H_ */
