/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * Polygon.h
 *
 *
 */

#ifndef Polygon_H_
#define Polygon_H_

#include "GeographicalCoordinates.h"
#include "GADShape.h"
#include <vector>
#include "Polygon_allOf.h"
#include "SupportedGADShapes.h"
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class Polygon {
 public:
  Polygon();
  virtual ~Polygon() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const Polygon& rhs) const;
  bool operator!=(const Polygon& rhs) const;

  /////////////////////////////////////////////
  /// Polygon members

  /// <summary>
  ///
  /// </summary>
  SupportedGADShapes getShape() const;
  void setShape(SupportedGADShapes const& value);
  /// <summary>
  ///
  /// </summary>
  std::vector<GeographicalCoordinates> getPointList() const;
  void setPointList(std::vector<GeographicalCoordinates> const& value);

  friend void to_json(nlohmann::json& j, const Polygon& o);
  friend void from_json(const nlohmann::json& j, Polygon& o);

 protected:
  SupportedGADShapes m_Shape;

  std::vector<GeographicalCoordinates> m_PointList;

  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* Polygon_H_ */
