/**
 * 3gpp-mo-lcs-notify
 * API for UE updated location information notification. © 2021, 3GPP
 * Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights
 * reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "PositioningMethod.h"
#include "Helpers.h"

#include <sstream>

namespace oai::nef::model {

PositioningMethod::PositioningMethod() {}

void PositioningMethod::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool PositioningMethod::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool PositioningMethod::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "PositioningMethod" : pathPrefix;

  return success;
}

bool PositioningMethod::operator==(const PositioningMethod& rhs) const {
  return true

      ;
}

bool PositioningMethod::operator!=(const PositioningMethod& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const PositioningMethod& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, PositioningMethod& o) {}

}  // namespace oai::nef::model
