/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * QosResourceType.h
 *
 *
 */

#ifndef QosResourceType_H_
#define QosResourceType_H_

#include "QosResourceType_anyOf.h"
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class QosResourceType {
 public:
  QosResourceType();
  virtual ~QosResourceType() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const QosResourceType& rhs) const;
  bool operator!=(const QosResourceType& rhs) const;

  /////////////////////////////////////////////
  /// QosResourceType members

  friend void to_json(nlohmann::json& j, const QosResourceType& o);
  friend void from_json(const nlohmann::json& j, QosResourceType& o);

 protected:
  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* QosResourceType_H_ */
