/**
 * 3gpp-service-parameter
 * API for AF service paramter © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */
/*
 * ServiceParameterDataPatch.h
 *
 *
 */

#ifndef ServiceParameterDataPatch_H_
#define ServiceParameterDataPatch_H_

#include <string>
#include <nlohmann/json.hpp>

namespace oai::nef::model {

/// <summary>
///
/// </summary>
class ServiceParameterDataPatch {
 public:
  ServiceParameterDataPatch();
  virtual ~ServiceParameterDataPatch() = default;

  /// <summary>
  /// Validate the current data in the model. Throws a ValidationException on
  /// failure.
  /// </summary>
  void validate() const;

  /// <summary>
  /// Validate the current data in the model. Returns false on error and writes
  /// an error message into the given stringstream.
  /// </summary>
  bool validate(std::stringstream& msg) const;

  bool operator==(const ServiceParameterDataPatch& rhs) const;
  bool operator!=(const ServiceParameterDataPatch& rhs) const;

  /////////////////////////////////////////////
  /// ServiceParameterDataPatch members

  /// <summary>
  ///
  /// </summary>
  std::string getParamOverPc5() const;
  void setParamOverPc5(std::string const& value);
  bool paramOverPc5IsSet() const;
  void unsetParamOverPc5();
  /// <summary>
  ///
  /// </summary>
  std::string getParamOverUu() const;
  void setParamOverUu(std::string const& value);
  bool paramOverUuIsSet() const;
  void unsetParamOverUu();

  friend void to_json(nlohmann::json& j, const ServiceParameterDataPatch& o);
  friend void from_json(const nlohmann::json& j, ServiceParameterDataPatch& o);

 protected:
  std::string m_ParamOverPc5;
  bool m_ParamOverPc5IsSet;
  std::string m_ParamOverUu;
  bool m_ParamOverUuIsSet;

  // Helper overload for validate. Used when one model stores another model and
  // calls it's validate.
  bool validate(std::stringstream& msg, const std::string& pathPrefix) const;
};

}  // namespace oai::nef::model

#endif /* ServiceParameterDataPatch_H_ */
