/**
 * Nnef_SMContext
 * Nnef SMContext Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SmallDataRateControlTimeUnit.h"
#include "Helpers.h"

#include <sstream>

namespace oai::nef::model {

SmallDataRateControlTimeUnit::SmallDataRateControlTimeUnit() {}

void SmallDataRateControlTimeUnit::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool SmallDataRateControlTimeUnit::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool SmallDataRateControlTimeUnit::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "SmallDataRateControlTimeUnit" : pathPrefix;

  return success;
}

bool SmallDataRateControlTimeUnit::operator==(
    const SmallDataRateControlTimeUnit& rhs) const {
  return true

      ;
}

bool SmallDataRateControlTimeUnit::operator!=(
    const SmallDataRateControlTimeUnit& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SmallDataRateControlTimeUnit& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, SmallDataRateControlTimeUnit& o) {}

}  // namespace oai::nef::model
