/**
 * Nnef_SMContext
 * Nnef SMContext Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SmContextStatus.h"
#include "Helpers.h"

#include <sstream>

namespace oai::nef::model {

SmContextStatus::SmContextStatus() {}

void SmContextStatus::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool SmContextStatus::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool SmContextStatus::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "SmContextStatus" : pathPrefix;

  return success;
}

bool SmContextStatus::operator==(const SmContextStatus& rhs) const {
  return

      ;
}

bool SmContextStatus::operator!=(const SmContextStatus& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SmContextStatus& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, SmContextStatus& o) {}

}  // namespace oai::nef::model
