/**
 * 3gpp-traffic-influence
 * API for AF traffic influence © 2021, 3GPP Organizational Partners (ARIB,
 * ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.1.2
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SubscribedEvent.h"
#include "Helpers.h"

#include <sstream>

namespace oai::nef::model {

SubscribedEvent::SubscribedEvent() {}

void SubscribedEvent::validate() const {
  std::stringstream msg;
  if (!validate(msg)) {
    throw org::openapitools::server::helpers::ValidationException(msg.str());
  }
}

bool SubscribedEvent::validate(std::stringstream& msg) const {
  return validate(msg, "");
}

bool SubscribedEvent::validate(
    std::stringstream& msg, const std::string& pathPrefix) const {
  bool success = true;
  const std::string _pathPrefix =
      pathPrefix.empty() ? "SubscribedEvent" : pathPrefix;

  return success;
}

bool SubscribedEvent::operator==(const SubscribedEvent& rhs) const {
  return

      ;
}

bool SubscribedEvent::operator!=(const SubscribedEvent& rhs) const {
  return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SubscribedEvent& o) {
  j = nlohmann::json();
}

void from_json(const nlohmann::json& j, SubscribedEvent& o) {}

}  // namespace oai::nef::model
