################################################################################
# Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The OpenAirInterface Software Alliance licenses this file to You under
# the OAI Public License, Version 1.1  (the "License"); you may not use this file
# except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.openairinterface.org/?page_id=698
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#-------------------------------------------------------------------------------
# For more information about the OpenAirInterface (OAI) Software Alliance:
#      contact@openairinterface.org
################################################################################

NEF =
{
    INSTANCE      = @INSTANCE@;         # 0 is the default
    PID_DIRECTORY = "@PID_DIRECTORY@";  # /var/run is the default


    SBI_INTERFACE :
    {
        # NEF binded interface for SBI interface (e.g., communication with other NFs e.g., AMF, SMF, UDM)
        INTERFACE_NAME = "@NEF_INTERFACE_NAME_FOR_SBI@";    
        IPV4_ADDRESS   = "read";
        PORT           = @NEF_INTERFACE_PORT_FOR_SBI@; # Default: 80
        HTTP2_PORT     = @NEF_INTERFACE_HTTP2_PORT_FOR_SBI@; 
        API_VERSION    = "@NEF_API_VERSION@";                
    };  
   
   AMF :
    {
      IPV4_ADDRESS = "@AMF_IPV4_ADDRESS@"; 
      PORT         = @AMF_PORT@;          # Default: 80
      HTTP2_PORT   = @AMF_HTTP2_PORT@;
      API_VERSION  = "@AMF_API_VERSION@";   
      FQDN         = "@AMF_FQDN@"           
    };               
   
   SMF :
    {
      IPV4_ADDRESS = "@SMF_IPV4_ADDRESS@";  
      PORT         = @SMF_PORT@;          # Default: 80
      HTTP2_PORT   = @AMF_HTTP2_PORT@;
      API_VERSION  = "@SMF_API_VERSION@";   
      FQDN         = "@SMF_FQDN@"           
    };
    
   UDM :
    {
      IPV4_ADDRESS = "@UDM_IPV4_ADDRESS@"; 
      PORT         = @UDM_PORT@;           # Default: 80
      HTTP2_PORT   = @UDM_HTTP2_PORT@;
      API_VERSION  = "@UDM_API_VERSION@";  
      FQDN         = "@UDM_FQDN@"          
    };
   
    # SUPPORT FEATURES
    SUPPORT_FEATURES:
    {
      # STRING, {"yes", "no"},
      USE_FQDN_DNS = "@USE_FQDN_DNS@";  # Set to yes if NEF will rely on a DNS to resolve FQDN
      USE_HTTP2 = "@USE_HTTP2@";    # Default: no
    }
   
};

