#/*
# * SPDX-License-Identifier: LicenseRef-CSSL-1.0
# */

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface NEF service
#   Valid for UBI 9.x | RHEL 9.x
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as oai-nef-builder

ARG EPEL_URL
ENV EPEL_URL=${EPEL_URL}

ENV IS_DOCKERFILE=1

# Copy the entitlements
COPY ./etc-pki-entitlement /etc/pki/entitlement
COPY ./rhsm-conf/rhsm.conf /etc/rhsm/rhsm.conf
COPY ./rhsm-ca/ /etc/rhsm/ca/

RUN rm -f /etc/rhsm-host && \
    microdnf install -y subscription-manager dnf && \
    subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms && \
    dnf update -y --allowerasing --skip-broken --nobest && \
    # To display the current version
    cat /etc/os-release && \
    dnf install -y \
        psmisc \
        git \
        diffutils \
        libasan \
        wget \
        file && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-nef
COPY . /openair-nef

# Installing and Building NEF
WORKDIR /openair-nef/build/scripts
RUN ./build_nef --install-deps --force
RUN ldconfig && \
    ./build_nef --clean --Verbose --build-type Release --jobs && \
    ldd /openair-nef/build/nef/build/nef && \
    mv /openair-nef/build/nef/build/nef /openair-nef/build/nef/build/oai_nef && \
    # Adapting the entrypoint to NEF NF
    sed -i -e "s@openair-nf-root-folder@openair-nef@g" \
           -e "s@nf-config-file@nef.conf@g" \
           ../common-build/docker-scripts/entrypoint.py && \
    # Remove entitlements and Subscription Manager configs
    rm -rf /etc/pki/entitlement
#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest as oai-nef
ENV TZ=Europe/Paris

# Copy the entitlements
COPY ./etc-pki-entitlement /etc/pki/entitlement
# Copy the subscription manager configurations
COPY --from=oai-nef-builder /etc/rhsm /etc/rhsm

# We install some debug tools for the moment in addition of mandatory libraries
RUN rm -f /etc/rhsm-host && \
    microdnf update -y && \
    microdnf install -y \
      python3 \
      python3-pip \
      tzdata \
      procps-ng \
      psmisc \
      net-tools \
      libicu \
      boost \
      libevent \
      findutils \
      libconfig && \
    pip3 install jinja2 && \
    microdnf clean all -y && \
    rm -rf /var/cache/yum /var/cache/dnf && \
    # Remove entitlements and Subscription Manager configs
    rm -rf /etc/pki/entitlement && \
    rm -rf /etc/rhsm

# Copying executable and generated libraries
WORKDIR /openair-nef/bin
COPY --from=oai-nef-builder \
    /openair-nef/build/nef/build/oai_nef \
    /openair-nef/build/common-build/docker-scripts/entrypoint.py \
    /openair-nef/scripts/healthcheck.sh \
    ./

COPY --from=oai-nef-builder \
# Copying only the packages built from source
    /usr/local/lib64/libpistache.so.0 \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib64/libfmt.so \
    /usr/lib64/

RUN ldconfig && \
    ldd /openair-nef/bin/oai_nef

# Copying template configuration files
# The configuration folder will be flat
WORKDIR /openair-nef/etc
COPY --from=oai-nef-builder /openair-nef/etc/nef.conf /openair-nef/etc/

WORKDIR /openair-nef

# expose ports
EXPOSE 80/tcp 9090/tcp
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-nef/bin/healthcheck.sh

ENTRYPOINT ["python3", "/openair-nef/bin/entrypoint.py"]
CMD ["/openair-nef/bin/oai_nef", "-c", "/openair-nef/etc/nef.conf", "-o"]
