#/*
# * SPDX-License-Identifier: LicenseRef-CSSL-1.0
# */

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface NEF service
#   Valid for Rocky Linux 9.+
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM docker.io/rockylinux:9 AS oai-nef-builder

ENV IS_DOCKERFILE=1

RUN dnf install 'dnf-command(config-manager)' -y && \
    dnf install epel-release -y && crb enable && \
    dnf update -y && \
    # here just to display the current version
    cat /etc/os-release && \
    dnf install -y \
        psmisc \
        git \
        diffutils \
        file \
        gcc-c++ \
        ninja-build \
        boost-devel \
        openssl-devel \
        openssl \
        wget \
        libasan && \
    echo "/usr/local/lib" > /etc/ld.so.conf.d/local-lib.conf && \
    echo "/usr/local/lib64" >> /etc/ld.so.conf.d/local-lib.conf

# Some GIT configuration command quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-nef/
COPY . /openair-nef

# Installing all the needed libraries/packages to build and run NEF
WORKDIR /openair-nef/build/scripts
RUN ./build_nef --install-deps --force

# Building NEF
WORKDIR /openair-nef/build/scripts
RUN ldconfig && \
    ./build_nef --clean --Verbose --build-type Release --jobs && \
    ldd /openair-nef/build/nef/build/nef && \
    mv /openair-nef/build/nef/build/nef /openair-nef/build/nef/build/oai_nef

FROM mikefarah/yq:latest as yq-source

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM docker.io/rockylinux:9-minimal as oai-nef
ENV TZ=Europe/Paris
# We install some debug tools for the moment in addition of mandatory libraries

RUN microdnf update -y && \
    microdnf install -y \
# Debug Tools that are not mandatory
      tzdata \
      procps-ng \
      psmisc \
      net-tools \
      iputils \
      tcpdump \
# Mandatory packages for the NF to run
      lksctp-tools \
      libicu \
      boost \
      libevent \
      findutils && \
    microdnf clean all -y && \
    rm -rf /var/cache/yum /var/cache/dnf

# Copying executable and generated libraries
WORKDIR /openair-nef/bin
COPY --from=oai-nef-builder \
    /openair-nef/build/nef/build/oai_nef \
    /openair-nef/scripts/healthcheck.sh \
    ./
COPY --from=yq-source /usr/bin/yq /usr/bin

COPY --from=oai-nef-builder \
    /usr/local/lib64/libpistache.so.0 \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib64/libspdlog.so \
    /usr/local/lib64/libfmt.so \
    /usr/local/lib64/libyaml-cpp.so.0.* \
    /usr/lib64/

RUN ldconfig && \
    ldd /openair-nef/bin/oai_nef

# Copying template configuration files
WORKDIR /openair-nef/etc
COPY --from=oai-nef-builder \
    /openair-nef/etc/config.yaml ./

WORKDIR /openair-nef

# expose ports
EXPOSE 80/tcp 9090/tcp
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-nef/bin/healthcheck.sh

CMD ["/openair-nef/bin/oai_nef", "-c", "/openair-nef/etc/config.yaml", "-o"]
