#/*
# * SPDX-License-Identifier: LicenseRef-CSSL-1.0
# */

#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface NEF service
#   Valid for Ubuntu-20.04 (focal),
#             Ubuntu-22.04 (jammy)
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BASE IMAGE
#---------------------------------------------------------------------
ARG BASE_IMAGE=ubuntu:jammy
FROM $BASE_IMAGE AS oai-nef-base

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ENV IS_DOCKERFILE=1
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      psmisc \
      git \
  && rm -rf /var/lib/apt/lists/*

# Some GIT configuration commands quite useful
RUN git config --global https.postBuffer 123289600 && \
    git config --global http.sslverify false

# Copying source code
WORKDIR /openair-nef/
COPY ./build/scripts /openair-nef/build/scripts
COPY ./build/common-build /openair-nef/build/common-build
COPY ./build/nef/CMakeLists.txt /openair-nef/build/nef/CMakeLists.txt

# Installing all the needed libraries/packages to build and run NEF
WORKDIR /openair-nef/build/scripts
RUN ./build_amf --install-deps --force

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM oai-nef-base AS oai-nef-builder
# Copying source code
ARG ENABLE_LTTNG=false

COPY . /openair-nef
# Building NEF
WORKDIR /openair-nef/build/scripts
RUN  if [ "$ENABLE_LTTNG" = "true" ]; then DEBIAN_FRONTEND=noninteractive apt-get install --yes \
        lttng-modules-dkms \
        liblttng-ust-dev \
        lttng-tools && \
        ldconfig && \
        ./build_amf --clean --Verbose --build-type Release --jobs --lttng; \
    else \
        ldconfig && \
        ./build_amf --clean --Verbose --build-type Release --jobs; \
    fi && \
    ldd /openair-nef/build/nef/build/nef && \
    mv /openair-nef/build/nef/build/nef /openair-nef/build/nef/build/oai_amf



#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM $BASE_IMAGE AS oai-nef
ARG TARGETPLATFORM
ARG VERSION=v4.47.1
ENV TARGETPLATFORM=${TARGETPLATFORM}

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ARG ENABLE_LTTNG=false

# We install some debug tools for the moment in addition of mandatory libraries
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
# Debug Tools that are not mandatory
      tzdata \
      psmisc \
      net-tools \
      tcpdump \
      iputils-ping \
      bc \
      wget \
# Mandatory packages for the NF to run
      libssh-4 \
      openssl \
      libbrotli1 \
      netbase \
# Ubuntu 20 --> libasan5
# Ubuntu 22 --> libasan6
#      libasan? \
      libgssapi-krb5-2 \
# Ubuntu 20 --> libldap-2.4-2
# Ubuntu 22 --> libldap-2.5-0
      libldap-2.?-? \
      libsctp1 \
      librtmp1 \
      libpsl5 \
      libcurl4-gnutls-dev \
# Ubuntu 20 --> boost71
# Ubuntu 22 --> boost74
      libboost-thread1.7?.0 \
      libboost-chrono1.7?.0 \
# lttng
  && if [ "$ENABLE_LTTNG" = "true" ]; then DEBIAN_FRONTEND=noninteractive apt-get install --yes liblttng-ust-dev; fi \
  && rm -rf /var/lib/apt/lists/*

# Copying executable and generated libraries
WORKDIR /openair-nef/bin
COPY --from=oai-nef-builder \
    /openair-nef/build/nef/build/oai_amf \
    /openair-nef/scripts/healthcheck.sh \
    ./

RUN echo "Target platform is: ${TARGETPLATFORM}" && \
    case "${TARGETPLATFORM}" in \
      "linux/amd64") BINARY="yq_linux_amd64"; ;; \
      "linux/arm64") BINARY="yq_linux_arm64"; ;; \
      *) echo "Unsupported platform"; exit 1; ;; \
    esac && \
    wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq && \
    chmod +x /usr/bin/yq

WORKDIR /usr/local/lib
COPY --from=oai-nef-builder \
# Copying only the packages built from source
    /usr/local/lib/libnghttp2.so.14 \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/local/lib/libpistache.so \
    /usr/local/lib/libfmt.so \
    /usr/local/lib/libyaml-cpp.so.0.? \
    ./

RUN ldconfig && \
    ldd /openair-nef/bin/oai_amf

# Copying template configuration files
WORKDIR /openair-nef/etc
COPY --from=oai-nef-builder \
    /openair-nef/etc/config.yaml ./

WORKDIR /openair-nef

ARG GIT_COMMIT

LABEL org.opencontainers.image.authors="OpenAirInterface <contact@openairinterface.org>" \
      org.opencontainers.image.vendor="OpenAirInterface Software Alliance" \
      org.opencontainers.image.licenses="Collaborative Standards Software License v1.0" \
      org.opencontainers.image.title="OAI NEF" \
      org.opencontainers.image.description="OpenAirInterface Access and Mobility Management Function" \
      org.opencontainers.image.revision="commit:${GIT_COMMIT}"

# expose ports
EXPOSE 80/tcp 9090/tcp
# healthcheck
HEALTHCHECK --interval=10s \
            --timeout=15s \
            --retries=6 \
    CMD /openair-nef/bin/healthcheck.sh

CMD ["/openair-nef/bin/oai_nef", "-c", "/openair-nef/etc/config.yaml", "-o"]
