#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface NEF service
#   Valid for Ubuntu-18.04 (bionic)
# The port exposed by container are 8080/tcp , 9090/tcp change it according to your setup
#
#---------------------------------------------------------------------

#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
FROM oai-nef-base:latest as oai-nef-builder

WORKDIR /openair-nef/
COPY . /openair-nef
RUN cp -Rf /openair-nef-ext-ref /openair-nef/build/ext

# Building NEF
WORKDIR /openair-nef/build/scripts
RUN ./build_nef --clean --Verbose --build-type Release --jobs && \
    ldd /openair-nef/build/nef/build/nef && \
    mv /openair-nef/build/nef/build/nef /openair-nef/build/nef/build/oai_nef

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM ubuntu:bionic as oai-nef
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris

# We install some debug tools for the moment in addition of mandatory libraries
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
      psmisc \
      net-tools \
      iputils-ping \
      bc \
      tzdata \
      libasan4 \
      libconfig++9v5 \
      libldap-2.4-2 \
      librtmp1 \
      libpsl5 \
  && rm -rf /var/lib/apt/lists/*

# Copying executable and generated libraries
WORKDIR /openair-nef/bin
COPY --from=oai-nef-builder \
    /openair-nef/build/nef/build/oai_nef \
    /openair-nef/scripts/entrypoint.sh \
    ./
COPY --from=oai-nef-builder \
    /usr/local/lib/libpistache.so \
    /usr/local/lib/libnghttp2_asio.so.1 \
    /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4 \
    /usr/lib/libboost_system.so.1.67.0 \
    /usr/lib/libboost_thread.so.1.67.0 \
    /usr/lib/libboost_chrono.so.1.67.0 \
    /usr/local/lib/

RUN ldconfig && \
    ldd /openair-nef/bin/oai_nef

# Copying template configuration files
COPY --from=oai-nef-builder /openair-nef/etc/nef.conf /openair-nef/etc/

WORKDIR /openair-nef

# expose ports
EXPOSE 80/tcp 9090/tcp

ENTRYPOINT ["/bin/bash","/openair-nef/bin/entrypoint.sh"]
CMD ["/openair-nef/bin/oai_nef", "-c", "/openair-nef/etc/nef.conf", "-o"]
