/**
 * 3gpp-analyticsexposure
 * API for Analytics Exposure. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * AnalyticsExposureAPIFetchAnalyticsInformationApiImpl.h
 *
 *
 */

#ifndef ANALYTICS_EXPOSURE_API_FETCH_ANALYTICS_INFORMATION_API_IMPL_H_
#define ANALYTICS_EXPOSURE_API_FETCH_ANALYTICS_INFORMATION_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <AnalyticsExposureAPIFetchAnalyticsInformationApi.h>

#include <pistache/optional.h>

#include "AnalyticsData.h"
#include "AnalyticsRequest.h"
#include "ProblemDetails.h"
#include <string>

namespace oai::nef::api {

using namespace oai::nef::model;

class AnalyticsExposureAPIFetchAnalyticsInformationApiImpl
    : public oai::nef::api::AnalyticsExposureAPIFetchAnalyticsInformationApi {
 public:
  explicit AnalyticsExposureAPIFetchAnalyticsInformationApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~AnalyticsExposureAPIFetchAnalyticsInformationApiImpl() override = default;

  void af_id_fetch_post(
      const std::string& afId, const AnalyticsRequest& analyticsRequest,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::nef::api

#endif
