/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "IndividualMonitoringEventSubscriptionApiImpl.h"

namespace oai {
namespace nef {
namespace api {

using namespace oai::nef::model;

IndividualMonitoringEventSubscriptionApiImpl::
    IndividualMonitoringEventSubscriptionApiImpl(
        const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : IndividualMonitoringEventSubscriptionApi(rtr) {}

void IndividualMonitoringEventSubscriptionApiImpl::
    delete_ind_monitoring_event_subscription(
        const std::string& scsAsId, const std::string& subscriptionId,
        Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void IndividualMonitoringEventSubscriptionApiImpl::
    fetch_ind_monitoring_event_subscription(
        const std::string& scsAsId, const std::string& subscriptionId,
        Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void IndividualMonitoringEventSubscriptionApiImpl::
    modify_ind_monitoring_event_subscription(
        const std::string& scsAsId, const std::string& subscriptionId,
        const std::vector<PatchItem>& patchItem,
        Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void IndividualMonitoringEventSubscriptionApiImpl::
    update_ind_monitoring_event_subscription(
        const std::string& scsAsId, const std::string& subscriptionId,
        const MonitoringEventSubscription& monitoringEventSubscription,
        Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace api
}  // namespace nef
}  // namespace oai
