/**
 * 3gpp-acs-pp
 * API for 5G ACS Parameter Provision. © 2021, 3GPP Organizational Partners
 * (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * IndividualACSConfigurationSubscriptionApiImpl.h
 *
 *
 */

#ifndef INDIVIDUAL_ACS_CONFIGURATION_SUBSCRIPTION_API_IMPL_H_
#define INDIVIDUAL_ACS_CONFIGURATION_SUBSCRIPTION_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <IndividualACSConfigurationSubscriptionApi.h>

#include <pistache/optional.h>

#include "AcsConfigurationData.h"
#include "ProblemDetails.h"
#include <string>

namespace oai::nef::api {

using namespace oai::nef::model;

class IndividualACSConfigurationSubscriptionApiImpl
    : public oai::nef::api::IndividualACSConfigurationSubscriptionApi {
 public:
  explicit IndividualACSConfigurationSubscriptionApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~IndividualACSConfigurationSubscriptionApiImpl() override = default;

  void af_id_subscriptions_subscription_id_delete(
      const std::string& afId, const std::string& subscriptionId,
      Pistache::Http::ResponseWriter& response);
  void af_id_subscriptions_subscription_id_get(
      const std::string& afId, const std::string& subscriptionId,
      Pistache::Http::ResponseWriter& response);
  void af_id_subscriptions_subscription_id_put(
      const std::string& afId, const std::string& subscriptionId,
      const AcsConfigurationData& acsConfigurationData,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::nef::api

#endif
