/**
 * Nnef_EventExposure
 * NEF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * IndividualSubscriptionDocumentApiImpl.h
 *
 *
 */

#ifndef INDIVIDUAL_SUBSCRIPTION_DOCUMENT_API_IMPL_H_
#define INDIVIDUAL_SUBSCRIPTION_DOCUMENT_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <IndividualSubscriptionDocumentApi.h>

#include "NefEventExposureSubsc.h"
#include "ProblemDetails.h"
#include <string>

namespace oai::nef::api {

using namespace oai::nef::model;

class IndividualSubscriptionDocumentApiImpl
    : public oai::nef::api::IndividualSubscriptionDocumentApi {
 public:
  explicit IndividualSubscriptionDocumentApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~IndividualSubscriptionDocumentApiImpl() override = default;

  void delete_individual_subcription(
      const std::string& subscriptionId,
      Pistache::Http::ResponseWriter& response);
  void get_individual_subcription(
      const std::string& subscriptionId,
      const std::optional<std::string>& suppFeat,
      Pistache::Http::ResponseWriter& response);
  void replace_individual_subcription(
      const std::string& subscriptionId,
      const NefEventExposureSubsc& nefEventExposureSubsc,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::nef::api

#endif
