/**
 * 3gpp-monitoring-event
 * API for Monitoring Event. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.2.0-alpha.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "MonitoringEventSubscriptionsApiImpl.h"

namespace oai {
namespace nef {
namespace api {

using namespace oai::nef::model;

MonitoringEventSubscriptionsApiImpl::MonitoringEventSubscriptionsApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : MonitoringEventSubscriptionsApi(rtr) {}

void MonitoringEventSubscriptionsApiImpl::create_monitoring_event_subscription(
    const std::string& scsAsId,
    const MonitoringEventSubscription& monitoringEventSubscription,
    Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}
void MonitoringEventSubscriptionsApiImpl::
    fetch_all_monitoring_event_subscriptions(
        const std::string& scsAsId,
        const std::optional<std::vector<IpAddr>>& ipAddrs,
        const std::optional<std::string>& ipDomain,
        const std::optional<std::vector<std::string>>& macAddrs,
        Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace api
}  // namespace nef
}  // namespace oai
