/**
 * Nnef_EventExposure
 * NEF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

#include "SubscriptionsCollectionApiImpl.h"

namespace oai {
namespace nef {
namespace api {

using namespace oai::nef::model;

SubscriptionsCollectionApiImpl::SubscriptionsCollectionApiImpl(
    const std::shared_ptr<Pistache::Rest::Router>& rtr)
    : SubscriptionsCollectionApi(rtr) {}

void SubscriptionsCollectionApiImpl::create_individual_subcription(
    const NefEventExposureSubsc& nefEventExposureSubsc,
    Pistache::Http::ResponseWriter& response) {
  response.send(Pistache::Http::Code::Ok, "Do some magic\n");
}

}  // namespace api
}  // namespace nef
}  // namespace oai
