/**
 * Nnef_EventExposure
 * NEF Event Exposure Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS,
 * CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * The version of the OpenAPI document: 1.0.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

/*
 * SubscriptionsCollectionApiImpl.h
 *
 *
 */

#ifndef SUBSCRIPTIONS_COLLECTION_API_IMPL_H_
#define SUBSCRIPTIONS_COLLECTION_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>
#include <optional>

#include <SubscriptionsCollectionApi.h>

#include "NefEventExposureSubsc.h"
#include "ProblemDetails.h"
#include <string>

namespace oai::nef::api {

using namespace oai::nef::model;

class SubscriptionsCollectionApiImpl
    : public oai::nef::api::SubscriptionsCollectionApi {
 public:
  explicit SubscriptionsCollectionApiImpl(
      const std::shared_ptr<Pistache::Rest::Router>& rtr);
  ~SubscriptionsCollectionApiImpl() override = default;

  void create_individual_subcription(
      const NefEventExposureSubsc& nefEventExposureSubsc,
      Pistache::Http::ResponseWriter& response);
};

}  // namespace oai::nef::api

#endif
